# Generated by Django 6.0.1 on 2026-01-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('retail_price', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('variants', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('seo_name', models.CharField(blank=True, max_length=400)),
                ('formatted_name_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.pdfdocument')),
            ],
        ),
    ]
