# Generated by Django 6.0 on 2026-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('retail_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('model_number', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('variants', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('post_excerpt', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
